"use client";

import { ArrowRight, Clock3, Mail, Search } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";
import { articles } from "@/data/resources";

const categories = ["All", "HR Tips", "Payroll", "Hiring", "Culture", "Product Updates"];
export default function ResourcesPage() { const [category, setCategory] = useState("All"); const [query, setQuery] = useState(""); const filtered = useMemo(() => articles.filter(article => (category === "All" || article.category === category) && `${article.title} ${article.excerpt}`.toLowerCase().includes(query.toLowerCase())), [category, query]); const featured = articles.find(article => article.featured)!; return <main>
  <section className="dot-grid px-6 pb-24 pt-24 lg:pb-32"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-muted">The HRGRIDNX resource room</p><h1 className="mt-6 max-w-4xl font-display text-6xl leading-[.88] sm:text-8xl">Useful ideas for making work work better.</h1><p className="mt-8 max-w-xl text-lg leading-8 text-muted">Practical guidance for people teams, leaders and the humans who make organisations happen.</p></div></section>
  <section className="mx-auto max-w-7xl px-6 py-24 lg:py-32"><Link href={`/resources/${featured.slug}`} className="grid overflow-hidden rounded-[30px] bg-ink text-white lg:grid-cols-[1.1fr_.9fr]"><div className="p-8 sm:p-12"><p className="text-xs font-bold uppercase tracking-[.18em] text-lime">Featured · {featured.category}</p><h2 className="mt-6 max-w-xl font-display text-5xl leading-none sm:text-6xl">{featured.title}</h2><p className="mt-6 max-w-lg text-base leading-7 text-white/60">{featured.excerpt}</p><span className="mt-8 inline-flex items-center gap-2 text-sm font-semibold">Read article <ArrowRight size={16} /></span></div><div className="dot-grid-light flex min-h-64 items-end bg-lime p-8 text-ink sm:p-12"><p className="font-display text-6xl leading-none">A better<br />first day.</p></div></Link></section>
  <section className="mx-auto max-w-7xl px-6 pb-24 lg:pb-32"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-center"><div className="flex flex-wrap gap-2">{categories.map(item => <button key={item} onClick={() => setCategory(item)} className={`rounded-full px-4 py-2 text-sm font-semibold ${category === item ? "bg-ink text-white" : "bg-sage text-ink"}`}>{item}</button>)}</div><label className="flex items-center gap-3 rounded-full border border-ink/10 bg-white px-4 py-2 text-sm text-muted"><Search size={16} /><input value={query} onChange={event => setQuery(event.target.value)} className="w-48 bg-transparent outline-none" placeholder="Search resources" /></label></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(article => <article key={article.slug} className="group rounded-3xl border border-ink/10 bg-white p-6 transition hover:-translate-y-1 hover:shadow-xl"><div className="flex justify-between text-[10px] font-bold uppercase tracking-widest text-muted"><span>{article.category}</span><span className="flex items-center gap-1"><Clock3 size={12} />{article.readTime}</span></div><h2 className="mt-12 font-display text-3xl leading-none">{article.title}</h2><p className="mt-4 text-sm leading-6 text-muted">{article.excerpt}</p><Link href={`/resources/${article.slug}`} className="mt-7 inline-flex items-center gap-2 text-sm font-bold">Read more <ArrowRight size={15} /></Link></article>)}</div></section>
  <section className="mx-6 mb-20 rounded-[30px] bg-sage px-6 py-14 sm:px-12 lg:mx-auto lg:max-w-7xl"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><Mail size={21} /><h2 className="mt-5 font-display text-5xl leading-none">A useful note, now and then.</h2><p className="mt-4 max-w-lg text-sm leading-6 text-muted">No noise. Just practical ideas for people, pay and the work around them.</p></div><form className="flex w-full max-w-md border-b border-ink/30 pb-3"><input type="email" required placeholder="Your work email" className="w-full bg-transparent text-sm outline-none placeholder:text-muted" /><button className="text-sm font-bold">Subscribe <ArrowRight className="ml-1 inline" size={15} /></button></form></div></section>
</main>; }
