import { ArrowLeft, ArrowRight, Clock3 } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { articles } from "@/data/resources";

export function generateStaticParams() { return articles.map(article => ({ slug: article.slug })); }
export const dynamicParams = false;
type Props = { params: Promise<{ slug: string }> };

export default async function ArticlePage({ params }: Props) { const { slug } = await params; const article = articles.find(item => item.slug === slug); if (!article) notFound(); const related = articles.filter(item => item.slug !== article.slug && item.category === article.category).slice(0, 3); return <main><section className="dot-grid px-6 pb-20 pt-20 lg:pb-28 lg:pt-28"><div className="mx-auto max-w-4xl"><Link href="/resources" className="inline-flex items-center gap-2 text-sm font-semibold"><ArrowLeft size={15} /> All resources</Link><p className="mt-12 text-xs font-bold uppercase tracking-[.18em] text-muted">{article.category}</p><h1 className="mt-5 font-display text-6xl leading-[.9] sm:text-8xl">{article.title}</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-muted">{article.excerpt}</p><div className="mt-7 flex items-center gap-4 text-xs font-semibold text-muted"><span>{article.date}</span><span className="flex items-center gap-1"><Clock3 size={14} />{article.readTime}</span></div></div></section><article className="mx-auto max-w-3xl px-6 py-20 lg:py-28">{article.body.map(section => <section key={section.heading} className="mb-14"><h2 className="font-display text-4xl leading-none sm:text-5xl">{section.heading}</h2>{section.paragraphs.map(paragraph => <p key={paragraph} className="mt-6 text-base leading-8 text-muted">{paragraph}</p>)}</section>)}<div className="rounded-3xl bg-lime p-7 sm:p-10"><p className="text-xs font-bold uppercase tracking-[.18em] text-ink/60">Put it into practice</p><p className="mt-4 font-display text-4xl leading-none">Good systems make good work easier.</p><Link href="/contact" className="mt-7 inline-flex items-center gap-2 text-sm font-bold">See HRGRIDNX in action <ArrowRight size={15} /></Link></div></article>{related.length > 0 && <section className="border-t section-rule px-6 py-20"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-muted">Keep reading</p><div className="mt-8 grid gap-4 md:grid-cols-3">{related.map(item => <Link key={item.slug} href={`/resources/${item.slug}`} className="rounded-2xl border border-ink/10 p-5 hover:bg-sage"><span className="text-xs font-bold text-muted">{item.readTime}</span><h3 className="mt-7 font-display text-3xl">{item.title}</h3></Link>)}</div></div></section>}</main>; }
