"use client";

import { ArrowRight, Filter, Users } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";

const stories = [
  { name: "Northstar Works", industry: "Technology", size: "Growing", result: "38% less time spent on people admin", copy: "A fictional product studio replaced scattered approvals with one calm operating rhythm." },
  { name: "Marlow & Co", industry: "Professional services", size: "Medium", result: "2 days faster onboarding", copy: "A fictional advisory team made every new starter feel expected before their first morning." },
  { name: "Fieldnote", industry: "Creative", size: "Small", result: "94% employee self-service", copy: "A fictional creative collective gave its people answers without adding another inbox." },
  { name: "Kinship Kitchens", industry: "Hospitality", size: "Growing", result: "99% payroll confidence", copy: "A fictional multi-site team connected shifts, leave and payroll in a single view." },
  { name: "Morrow Health", industry: "Healthcare", size: "Medium", result: "12 hours back every month", copy: "A fictional care network brought sensitive people processes into clearer focus." },
  { name: "Louder Learning", industry: "Education", size: "Small", result: "3x more goal check-ins", copy: "A fictional learning team made progress conversations part of the normal week." },
];
const industries = ["All industries", "Technology", "Professional services", "Creative", "Hospitality", "Healthcare", "Education"];
const sizes = ["All sizes", "Small", "Growing", "Medium"];

export default function CustomersPage() { const [industry, setIndustry] = useState("All industries"); const [size, setSize] = useState("All sizes"); const filtered = useMemo(() => stories.filter(story => (industry === "All industries" || story.industry === industry) && (size === "All sizes" || story.size === size)), [industry, size]); return <main>
  <section className="dot-grid px-6 pb-24 pt-24 lg:pb-32"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-muted">Customer stories</p><h1 className="mt-6 max-w-4xl font-display text-6xl leading-[.88] sm:text-8xl">Good work looks different when the pieces connect.</h1><p className="mt-8 max-w-xl text-lg leading-8 text-muted">Explore how fictional teams across industries use HRGRIDNX to make people operations more human, useful and ready for what is next.</p></div></section>
  <section className="mx-auto max-w-7xl px-6 py-24 lg:py-32"><div className="flex flex-col justify-between gap-7 lg:flex-row lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-muted">Browse the wall</p><h2 className="mt-4 font-display text-5xl leading-none sm:text-6xl">Stories worth sharing.</h2></div><div className="flex flex-wrap items-center gap-2 text-sm"><Filter size={16} className="mr-1 text-muted" />{industries.map(option => <button key={option} onClick={() => setIndustry(option)} className={`rounded-full px-3 py-2 ${industry === option ? "bg-ink text-white" : "bg-sage text-ink"}`}>{option}</button>)}</div></div><div className="mt-5 flex flex-wrap gap-2 text-xs font-semibold text-muted"><span className="py-2">Company size:</span>{sizes.map(option => <button key={option} onClick={() => setSize(option)} className={`rounded-full border px-3 py-2 ${size === option ? "border-ink bg-ink text-white" : "border-ink/10"}`}>{option}</button>)}</div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{filtered.map((story, index) => <article key={story.name} className={`rounded-[28px] border border-ink/10 p-6 ${index % 4 === 0 ? "bg-lime" : "bg-white"}`}><div className="flex items-center justify-between"><span className="text-sm font-bold tracking-tight">{story.name}</span><span className="rounded-full bg-ink/10 px-2 py-1 text-[10px] font-bold uppercase tracking-widest">{story.industry}</span></div><div className="mt-16"><p className="font-display text-4xl leading-none">{story.result}</p><p className="mt-5 text-sm leading-6 text-muted">{story.copy}</p></div><Link href="/contact" className="mt-8 inline-flex items-center gap-2 text-sm font-bold">Read the story <ArrowRight size={15} /></Link></article>)}</div>{filtered.length === 0 && <div className="mt-10 rounded-3xl bg-sage p-10 text-center text-muted">No stories match both filters yet. Try widening the view.</div>}</section>
  <section className="bg-ink px-6 py-20 text-white lg:py-24"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-10 sm:grid-cols-4"><div><p className="font-display text-5xl text-lime">38%</p><p className="mt-2 text-xs text-white/55">less admin time</p></div><div><p className="font-display text-5xl text-lime">3x</p><p className="mt-2 text-xs text-white/55">faster onboarding</p></div><div><p className="font-display text-5xl text-lime">94%</p><p className="mt-2 text-xs text-white/55">self-service adoption</p></div><div><p className="font-display text-5xl text-lime">1</p><p className="mt-2 text-xs text-white/55">connected grid</p></div></div></section>
  <section className="mx-auto max-w-7xl px-6 py-24 lg:py-32"><div className="flex items-center gap-3"><Users size={19} /><p className="text-xs font-bold uppercase tracking-[.18em] text-muted">The testimonial wall</p></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{[["The visibility changed the way our managers lead. They see the day before the day sees them.", "Amina Cole", "Operations, Northstar Works"], ["We stopped treating onboarding like an event and started treating it like a relationship.", "Nadia Morgan", "People, Marlow & Co"], ["The best software decision is the one that gives people their attention back.", "Theo Grant", "Founder, Fieldnote"], ["Payroll is finally a rhythm we trust instead of a deadline we fear.", "Jon Bell", "Finance, Kinship Kitchens"], ["Clear systems gave our culture room to breathe.", "Maya Singh", "Team Lead, Morrow Health"], ["Everyone knows where to look now. That is a bigger win than it sounds.", "Elena Rossi", "Director, Louder Learning"]].map(([quote, name, role]) => <div key={name} className="rounded-3xl border border-ink/10 bg-[#eaf0e4] p-6"><p className="font-display text-3xl leading-tight">“{quote}”</p><p className="mt-8 text-sm font-semibold">{name}</p><p className="mt-1 text-xs text-muted">{role} · Placeholder quote</p></div>)}</div></section>
  <section className="px-6 pb-24"><div className="mx-auto max-w-7xl rounded-[30px] bg-lime p-8 sm:p-12"><h2 className="max-w-2xl font-display text-5xl leading-none sm:text-6xl">Your team could be the next good story.</h2><Link href="/contact" className="mt-8 inline-flex h-12 items-center gap-2 rounded-full bg-ink px-5 text-sm font-semibold text-white">Get started <ArrowRight size={16} /></Link></div></section>
</main>; }
