import { ArrowRight, ChevronRight, Sparkles } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { roleList, roles, type RoleSlug } from "@/data/roles";

export function generateStaticParams() { return roleList.map(role => ({ role: role.slug })); }
export const dynamicParams = false;
type Props = { params: Promise<{ role: RoleSlug }> };

export default async function RolePage({ params }: Props) {
  const { role: slug } = await params;
  const role = roles[slug];
  if (!role) notFound();
  return (
    <main>
      <section className={`relative overflow-hidden px-6 pb-24 pt-24 lg:pb-32 ${role.accent === "lime" ? "bg-lime" : "bg-sage/60"}`}>
        <div className="absolute right-[-80px] top-[-100px] h-[360px] w-[360px] rounded-full border-[55px] border-white/40" />
        <div className="relative mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.1fr_.9fr]">
          <div><Link href="/solutions" className="text-xs font-bold uppercase tracking-[.18em] text-muted">Solutions / {role.name}</Link><h1 className="mt-7 max-w-3xl font-display text-6xl leading-[.88] tracking-tight sm:text-8xl">{role.headline}</h1><p className="mt-8 max-w-xl text-lg leading-8 text-muted">{role.description}</p><Link href="/contact" className="mt-9 inline-flex h-12 items-center gap-2 rounded-full bg-ink px-5 text-sm font-semibold text-white">Get started <ArrowRight size={16} /></Link></div>
          <div className="relative mx-auto h-[360px] w-full max-w-sm"><div className="absolute inset-5 rotate-3 rounded-[28px] border border-ink/10 bg-white p-6 shadow-2xl"><div className="flex items-center justify-between border-b border-ink/10 pb-4"><span className="text-xs font-bold">{role.name} view</span><span className="h-2 w-2 rounded-full bg-lime" /></div><div className="mt-7 flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-full bg-sage"><Sparkles size={20} /></span><div><p className="text-sm font-semibold">Your day, in focus</p><p className="mt-1 text-[10px] text-muted">Everything worth knowing</p></div></div><div className="mt-8 space-y-3">{role.features.slice(0, 3).map(feature => <div key={feature[0]} className="rounded-xl bg-[#faf8f3] p-3"><p className="text-xs font-semibold">{feature[0]}</p><p className="mt-1 text-[10px] text-muted">Ready when you are</p></div>)}</div><div className="mt-6 h-2 rounded-full bg-sage"><div className="h-full w-4/5 rounded-full bg-ink" /></div></div><div className="absolute bottom-2 left-0 rounded-2xl bg-ink p-4 text-white shadow-xl"><p className="text-[10px] uppercase tracking-widest text-white/55">In sync</p><p className="mt-2 font-display text-3xl text-lime">{role.name === "Finance Manager" ? "99.8%" : "86%"}</p></div></div>
        </div>
      </section>
      <section className="mx-auto max-w-7xl px-6 py-24 lg:py-32"><p className="text-xs font-bold uppercase tracking-[.18em] text-muted">A day in the life</p><h2 className="mt-5 max-w-2xl font-display text-5xl leading-none sm:text-6xl">A little more flow in every part of the day.</h2><div className="mt-14 grid gap-6 md:grid-cols-3">{role.timeline.map((item, index) => <div key={item.time} className="relative border-t-2 border-ink pt-6"><span className="text-xs font-bold text-muted">{item.time}</span><h3 className="mt-8 font-display text-3xl">{item.title}</h3><p className="mt-3 text-sm leading-6 text-muted">{item.copy}</p>{index < 2 && <ChevronRight className="absolute right-0 top-5 hidden text-ink/30 md:block" />}</div>)}</div></section>
      <section className="bg-sage/50 px-6 py-24 lg:py-32"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-muted">Designed around your work</p><h2 className="mt-5 max-w-2xl font-display text-5xl leading-none sm:text-6xl">Six ways {role.name.toLowerCase()}s get a better day.</h2><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{role.features.map(feature => { const Icon = feature[2]; return <div key={feature[0]} className="rounded-3xl border border-ink/10 bg-white p-6"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-lime"><Icon size={20} /></span><h3 className="mt-10 font-display text-3xl">{feature[0]}</h3><p className="mt-3 text-sm leading-6 text-muted">{feature[1]}</p></div>; })}</div></div></section>
      <section className="mx-auto max-w-7xl px-6 py-24 lg:py-32"><div className="grid gap-12 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-muted">The shift</p><h2 className="mt-5 font-display text-5xl leading-none sm:text-6xl">From keeping up to moving forward.</h2></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-3xl border border-ink/10 p-6"><p className="text-xs font-bold uppercase tracking-widest text-muted">Before</p><p className="mt-6 font-display text-3xl">Scattered updates and small tasks that become big distractions.</p></div><div className="rounded-3xl bg-ink p-6 text-white"><p className="text-xs font-bold uppercase tracking-widest text-lime">After</p><p className="mt-6 font-display text-3xl">A clear view, a confident next move and time back in the day.</p></div></div></div><div className="mt-16 max-w-3xl rounded-[28px] bg-lime p-8 sm:p-12"><p className="font-display text-4xl leading-tight sm:text-5xl">“{role.quote}”</p><p className="mt-7 text-sm font-semibold">{role.quotePerson}</p><p className="mt-2 text-[10px] font-bold uppercase tracking-widest text-ink/60">Placeholder customer quote</p></div></section>
      <section className="border-t section-rule px-6 py-24"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-muted">Keep exploring</p><h2 className="mt-5 font-display text-5xl leading-none">Built for every role in the room.</h2><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{roleList.filter(item => item.slug !== role.slug).slice(0, 3).map(other => <Link key={other.slug} href={`/solutions/${other.slug}`} className="group rounded-2xl border border-ink/10 p-5 transition hover:-translate-y-1 hover:bg-sage"><div className="flex items-center justify-between"><span className="text-sm font-bold">{other.name}</span><ArrowRight size={16} /></div><p className="mt-8 font-display text-2xl">{other.headline}</p></Link>)}</div></div></section>
      <section className="px-6 pb-24"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 rounded-[30px] bg-ink p-8 text-white sm:p-12 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-lime">Ready for less friction?</p><h2 className="mt-5 max-w-2xl font-display text-5xl leading-none sm:text-6xl">Give your role a better way to work.</h2></div><Link href="/contact" className="inline-flex h-12 items-center gap-2 rounded-full bg-lime px-5 text-sm font-semibold text-ink">Get started <ArrowRight size={16} /></Link></div></section>
    </main>
  );
}
