"use client";

import { AnimatePresence, motion } from "framer-motion";
import { ArrowRight, Check, ChevronDown, Minus, Sparkles } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";
import { addOns, comparisonGroups, plans, type BillingCycle } from "@/data/pricing";

const pricingFaqs = [["Can I change plans later?", "Yes. Your plan can grow or simplify with your organisation, and we will help you make the change cleanly."], ["Is there a free trial?", "Every plan starts with a guided demo and a clear setup conversation, so you know exactly what you are choosing before you commit."], ["How does yearly billing work?", "Yearly billing is paid upfront and saves 20% compared with paying monthly."], ["What counts as a person?", "Any active employee or team member with access to HRGRIDNX counts as a person on your plan."], ["Do you offer implementation help?", "Yes. Every team gets a thoughtful start, with managed onboarding available for organisations that want more hands-on support."]];

function Value({ value }: { value: boolean | string }) { if (value === true) return <Check size={17} className="text-ink" />; if (value === false) return <Minus size={16} className="text-ink/20" />; return <span className="text-xs font-semibold text-muted">{value}</span>; }
function Heading({ eyebrow, title, copy }: { eyebrow: string; title: string; copy?: string }) { return <div><p className="text-xs font-bold uppercase tracking-[.18em] text-muted">{eyebrow}</p><h2 className="mt-4 max-w-3xl font-display text-5xl leading-[.95] sm:text-6xl">{title}</h2>{copy && <p className="mt-5 max-w-xl text-base leading-7 text-muted">{copy}</p>}</div>; }

export default function PricingPage() {
  const [cycle, setCycle] = useState<BillingCycle>("monthly");
  const [openGroups, setOpenGroups] = useState<string[]>(comparisonGroups.map(group => group.name));
  const [quiz, setQuiz] = useState({ size: "", need: "", budget: "" });
  const [faq, setFaq] = useState<number | null>(0);
  const recommendation = useMemo(() => { if (quiz.need === "complex" || quiz.size === "large") return "Enterprise"; if (quiz.size === "growing" || quiz.need === "payroll") return "Growth"; if (quiz.size === "small" && quiz.budget === "careful") return "Starter"; return null; }, [quiz]);
  const answer = (key: "size" | "need" | "budget", value: string) => setQuiz(current => ({ ...current, [key]: value }));
  return <main>
    <section className="dot-grid px-6 pb-24 pt-24 lg:pb-32"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-muted">Simple, transparent pricing</p><h1 className="mt-6 max-w-4xl font-display text-6xl leading-[.88] sm:text-8xl">A better people platform should be easy to choose.</h1><p className="mt-8 max-w-xl text-lg leading-8 text-muted">Start with what your team needs today. Add depth as you grow. No surprise fees, no pricing maze.</p><div className="mt-9 flex items-center gap-3 rounded-full border border-ink/10 bg-white p-1 text-sm font-semibold shadow-sm"><button onClick={() => setCycle("monthly")} className={`rounded-full px-5 py-3 ${cycle === "monthly" ? "bg-ink text-white" : "text-muted"}`}>Monthly</button><button onClick={() => setCycle("yearly")} className={`rounded-full px-5 py-3 ${cycle === "yearly" ? "bg-ink text-white" : "text-muted"}`}>Yearly <span className="ml-1 text-lime">Save 20%</span></button></div></div></section>
    <section className="mx-auto max-w-7xl px-6 pb-24 lg:pb-32"><div className="grid gap-4 lg:grid-cols-3">{plans.map(plan => <div key={plan.id} className={`relative rounded-[28px] border p-7 ${plan.highlighted ? "border-ink bg-ink text-white shadow-[0_20px_60px_rgba(15,42,36,.18)]" : "border-ink/10 bg-white"}`}>{plan.highlighted && <span className="absolute right-6 top-6 rounded-full bg-lime px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-ink">Most popular</span>}<p className={`text-xs font-bold uppercase tracking-widest ${plan.highlighted ? "text-lime" : "text-muted"}`}>{plan.name}</p><h2 className="mt-5 font-display text-4xl">{plan.description}</h2><div className="mt-8 flex items-baseline gap-2">{plan.monthly === null ? <span className="font-display text-5xl">Custom</span> : <><AnimatePresence mode="wait"><motion.span key={`${plan.id}-${cycle}`} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }} className="font-display text-6xl">£{cycle === "monthly" ? plan.monthly : plan.yearly}</motion.span></AnimatePresence><span className={`text-xs ${plan.highlighted ? "text-white/60" : "text-muted"}`}>/ person / month</span></>}</div><p className={`mt-2 text-xs ${plan.highlighted ? "text-white/55" : "text-muted"}`}>{cycle === "yearly" && plan.monthly !== null ? "Billed yearly" : plan.note}</p><Link href="/contact" className={`mt-8 inline-flex h-12 w-full items-center justify-center gap-2 rounded-full text-sm font-semibold ${plan.highlighted ? "bg-lime text-ink" : "bg-ink text-white"}`}>{plan.id === "enterprise" ? "Talk to us" : "Get started"}<ArrowRight size={16} /></Link><ul className={`mt-8 space-y-4 border-t pt-7 text-sm ${plan.highlighted ? "border-white/15" : "border-ink/10"}`}>{plan.features.map(feature => <li key={feature} className="flex items-center gap-3"><Check size={16} className={plan.highlighted ? "text-lime" : "text-ink"} />{feature}</li>)}</ul></div>)}</div></section>
    <section className="bg-sage/55 px-6 py-24 lg:py-32"><div className="mx-auto max-w-7xl"><Heading eyebrow="Compare the detail" title="Everything you need to make a confident call." copy="Plans are simple. The detail is here when you need to go deeper." /><div className="mt-12 overflow-x-auto rounded-[24px] border border-ink/10 bg-white"><div className="sticky left-0 top-0 grid min-w-[760px] grid-cols-[minmax(230px,1fr)_150px_150px_150px] border-b border-ink/10 bg-white p-5 text-xs font-bold uppercase tracking-widest"><span>Feature</span><span>Starter</span><span className="text-ink">Growth</span><span>Enterprise</span></div>{comparisonGroups.map(group => <div key={group.name} className="min-w-[760px]"><button onClick={() => setOpenGroups(current => current.includes(group.name) ? current.filter(name => name !== group.name) : [...current, group.name])} className="grid w-full grid-cols-[minmax(230px,1fr)_450px] items-center border-b border-ink/10 bg-[#faf8f3] p-5 text-left text-sm font-bold"><span>{group.name}</span><ChevronDown size={17} className={`justify-self-end transition-transform ${openGroups.includes(group.name) ? "rotate-180" : ""}`} /></button><AnimatePresence initial={false}>{openGroups.includes(group.name) && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden">{group.features.map(feature => <div key={feature.name} className="grid grid-cols-[minmax(230px,1fr)_150px_150px_150px] items-center border-b border-ink/10 p-5 text-sm"><span>{feature.name}</span><Value value={feature.starter} /><Value value={feature.growth} /><Value value={feature.enterprise} /></div>)}</motion.div>}</AnimatePresence></div>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-6 py-24 lg:py-32"><Heading eyebrow="Add what you need" title="Helpful extras, when the moment calls for them." /><div className="mt-10 grid gap-4 md:grid-cols-3">{addOns.map(([name, copy]) => <div key={name} className="rounded-3xl border border-ink/10 bg-white p-6"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-lime"><Sparkles size={19} /></span><h3 className="mt-10 font-display text-3xl">{name}</h3><p className="mt-3 text-sm leading-6 text-muted">{copy}</p><Link href="/contact" className="mt-7 inline-flex items-center gap-2 text-sm font-bold">Learn more <ArrowRight size={15} /></Link></div>)}</div></section>
    <section className="bg-ink px-6 py-24 text-white lg:py-32"><div className="mx-auto max-w-4xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-lime">A little help choosing</p><h2 className="mt-4 font-display text-5xl leading-none sm:text-6xl">Which plan fits me?</h2><div className="mt-12 grid gap-8 md:grid-cols-3">{[["size", "How big is your team?", [["small", "Up to 25"], ["growing", "26–250"], ["large", "250+"]]], ["need", "What matters most right now?", [["simple", "Get organised"], ["payroll", "Time and pay"], ["complex", "Complex workflows"]]], ["budget", "How do you want to start?", [["careful", "Keep it lean"], ["balanced", "Invest for growth"], ["tailored", "Build around us"]]]].map(([key, question, options]) => <div key={key as string}><p className="text-sm font-semibold">{question as string}</p><div className="mt-4 space-y-2">{(options as string[][]).map(([value, label]) => <button key={value} onClick={() => answer(key as "size" | "need" | "budget", value)} className={`w-full rounded-xl border px-4 py-3 text-left text-sm ${quiz[key as "size" | "need" | "budget"] === value ? "border-lime bg-lime text-ink" : "border-white/15 text-white/70 hover:border-white/40"}`}>{label}</button>)}</div></div>)}</div>{recommendation && <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="mt-12 flex flex-col justify-between gap-5 rounded-2xl bg-lime p-5 text-ink sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-widest">Our recommendation</p><p className="mt-1 font-display text-3xl">{recommendation}</p></div><Link href="/contact" className="inline-flex items-center gap-2 text-sm font-bold">See it in action <ArrowRight size={16} /></Link></motion.div>}</div></section>
    <section className="mx-auto max-w-3xl px-6 py-24"><Heading eyebrow="Pricing questions" title="The useful stuff, upfront." /><div className="mt-10 border-t border-ink/15">{pricingFaqs.map(([question, answer], index) => <div key={question} className="border-b border-ink/15"><button onClick={() => setFaq(faq === index ? null : index)} className="flex w-full justify-between py-5 text-left text-sm font-semibold">{question}<ChevronDown size={18} className={faq === index ? "rotate-180" : ""} /></button>{faq === index && <p className="pb-5 text-sm leading-7 text-muted">{answer}</p>}</div>)}</div></section>
    <section className="dot-grid mx-6 mb-20 rounded-[32px] bg-lime px-6 py-16 sm:px-12 lg:mx-auto lg:max-w-7xl"><h2 className="max-w-2xl font-display text-5xl leading-none sm:text-7xl">Make the next people decision an easy one.</h2><Link href="/contact" className="mt-8 inline-flex h-12 items-center gap-2 rounded-full bg-ink px-5 text-sm font-semibold text-white">Get started <ArrowRight size={16} /></Link></section>
  </main>;
}
